import { AppData } from '@/types';

export const DEFAULT_APP_DATA: AppData = {
  apiKey: '',
  persona: { name: 'Switch Dean', specialties: 'male findom, foot worship, wallet drain', style: 'strict' },
  subs: [],
  redflags: [],
  customPrices: [],
  calendar: [],
  goal: { target: 0, current: 0 },
  responses: {
    initial: 'Loading...',
    tribute: 'Loading...',
    excuse: 'Loading...',
    task: 'Loading...',
    punishment: 'Loading...',
  },
  screenTime: 0,
  timerStart: null,
  checklist: {
    date: new Date().toISOString().split('T')[0],
    tasks: [
      'AM medication',
      'PM medication',
      'Shower',
      'Spend 30 minutes cleaning',
      '30 minute workout',
      'Post on Twitter 3x',
      'Take pictures for content',
      'Post/comment on Reddit',
      'Post on LoyalFans',
      'Engage with subs on social media',
      'Check analytics and earnings',
      'Create 1 video for clips',
      'Respond to messages within 2 hours',
      'Plan tomorrow\'s content',
      'Update sub profiles/notes',
      'Review red flag database',
      'Drink 8 glasses of water',
      'Eat a healthy meal',
    ],
    completed: [],
    weeklyTasks: DEFAULT_WEEKLY_TASKS,
    weeklyCompleted: [],
  },
  uploadedImageData: null,
  tributes: [],
  profile: {
    displayName: '',
    bio: '',
    persona: 'dominant'
  },
  settings: {
    emailNotifications: true,
    pushNotifications: true,
    dailyReminders: true,
    profileVisibility: 'private',
    dataSharing: false,
    theme: 'dark'
  },
  subscription: 'free'
};

export const DEFAULT_CHECKLIST_TASKS = [
  'AM medication',
  'PM medication',
  'Shower',
  'Spend 30 minutes cleaning',
  '30 minute workout',
  'Post on Twitter 3x',
  'Take pictures for content',
  'Post/comment on Reddit',
  'Post on LoyalFans',
  'Engage with subs on social media',
  'Check analytics and earnings',
  'Create 1 video for clips',
  'Respond to messages within 2 hours',
  'Plan tomorrow\'s content',
  'Update sub profiles/notes',
  'Review red flag database',
  'Drink 8 glasses of water',
  'Eat a healthy meal',
];

export const DEFAULT_WEEKLY_TASKS = [
  'Review weekly earnings and set goals',
  'Deep clean content creation space',
  'Plan content calendar for next week',
  'Update pricing and service menus',
  'Review and update sub tier levels',
  'Create special offers for loyal subs',
  'Post longer-form content (blog/article)',
  'Host live session or Q&A',
  'Update social media bios and links',
  'Review platform analytics and trends',
  'Create themed content bundles',
  'Reach out to inactive subs',
  'Backup all content and data',
  'Review and update red flag database',
  'Plan self-care and relaxation time',
  'Update equipment/supplies as needed',
  'Network with other creators',
  'Research new content ideas/trends',
  'Review tax/financial planning',
  'Set weekly tribute targets'
];