import { AppData } from '@/types';

export const DEFAULT_APP_DATA: AppData = {
  apiKey: '',
  persona: { name: 'Switch Dean', specialties: 'male findom, foot worship, wallet drain', style: 'strict' },
  subs: [],
  redflags: [],
  customPrices: [],
  calendar: [],
  goal: { target: 0, current: 0 },
  responses: {
    initial: 'Loading...',
    tribute: 'Loading...',
    excuse: 'Loading...',
    task: 'Loading...',
    punishment: 'Loading...',
  },
  screenTime: 0,
  timerStart: null,
  checklist: {
    date: new Date().toISOString().split('T')[0],
    tasks: [
      'Take AM medication',
      '30 minute workout',
      'Shower',
      'Spend 30 minutes cleaning',
      'Eat a healthy meal',
      'Drink 8 glasses of water',
      'Post on Twitter 3x',
      'Take pictures for content',
      'Post/comment on Reddit',
      'Post on LoyalFans',
      'Engage with subs on social media',
      'Check analytics',
      'Plan next content',
      'Take PM medication',
      'Review daily earnings',
      'Update task tracker',
    ],
    completed: [],
  },
  uploadedImageData: null,
  tributes: [],
  profile: {
    displayName: '',
    bio: '',
    persona: 'dominant'
  },
  settings: {
    emailNotifications: true,
    pushNotifications: true,
    dailyReminders: true,
    profileVisibility: 'private',
    dataSharing: false,
    theme: 'dark'
  },
  subscription: 'free'
};

export const DEFAULT_CHECKLIST_TASKS = [
  'Take AM medication',
  '30 minute workout',
  'Shower',
  'Spend 30 minutes cleaning',
  'Eat a healthy meal',
  'Drink 8 glasses of water',
  'Post on Twitter 3x',
  'Take pictures for content',
  'Post/comment on Reddit',
  'Post on LoyalFans',
  'Engage with subs on social media',
  'Check analytics',
  'Plan next content',
  'Take PM medication',
  'Review daily earnings',
  'Update task tracker',
];

export const DEFAULT_WEEKLY_TASKS = [
  'Deep clean living space',
  'Meal prep for the week',
  'Review weekly earnings and goals',
  'Plan content schedule for next week',
  'Update subscription prices if needed',
  'Review and update red flag list',
  'Check all social media analytics',
  'Create 5 new content pieces',
  'Respond to all fan messages',
  'Update profile/bio on platforms',
  'Research new content trends',
  'Backup all content and data',
  'Review sub performance and engagement',
  'Plan special offers/promotions',
  'Self-care and relaxation time',
];