import { AppData } from '@/types';
import { DEFAULT_WEEKLY_TASKS, DEFAULT_CHECKLIST_TASKS } from './index';

export const DEFAULT_APP_DATA: AppData = {
  subs: [],
  tributes: [],
  redflags: [],
  checklists: [],
  customPrices: [],
  calendarEvents: [],
  calendar: [],
  goal: { weekly: 0, monthly: 0 },
  profile: {
    first_name: '',
    bio: '',
    persona: 'dominant',
    gender: 'male',
    energy: 'masculine',
    onboardingCompleted: false,
    onboardingCompletedAt: null,
  },
  settings: {
    emailNotifications: true,
    pushNotifications: true,
    dailyReminders: true,
    profileVisibility: 'private',
    dataSharing: false,
    theme: 'dark',
  },
  responses: {},
  apiKey: '',
  persona: 'dominant',
  screenTime: 0,
  timerStart: null,
  uploadedImageData: null,
  checklist: {
    id: '',
    date: new Date().toISOString().split('T')[0],
    tasks: [],
    completed: [],
    weeklyTasks: DEFAULT_WEEKLY_TASKS,
    weeklyCompleted: [],
  },
  subscription: '',
};